# Generated by Django 3.2.12 on 2022-03-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20220320_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_there',
            field=models.BooleanField(default=False),
        ),
    ]
