# Generated by Django 3.2.12 on 2022-03-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_about_is_there'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='description',
            new_name='about',
        ),
    ]
